### ISSUE TITLE
Failing clj-test on Erlang 21.3

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#372]
```
  1) clj-tests:comp_test/0
     Failure/Error: ?assertEqual([48,46,53], (car (io_lib:format (126 46 49 102) (backquote ((comma asin-result))))))
       expected: "0.5"
            got: 48
     %% eunit_proc.erl:325:in `eunit_proc:with_timeout/3`
     Output: 
     Output: 
```

For full run, see: https://travis-ci.org/oubiwann/lfe/jobs/529378169 where you can note that it passes for all other previous versions ...
